### PR TITLE
Gas based AI

### PR DESCRIPTION
**Pull request by SafakOnol**
### WHAT
Add GAS to AI character for health and shield

### WHY
To have a uniform damage-health system among all actors in the game

### HOW
Ability system added into AI C++ class and initialized in BP

### CODE REVIEW

**Comment by SafakOnol** [comment]
@antoniukoff, please take a look at the BP RangeAI and confirm if my changes didn't break anything you implemented.

**Review by MashdorDev — CHANGES_REQUESTED** [review]
Hey @SafakOnol the changes look great, just a few notes - 

1. the camera changed from being on rail to 3 person camera
2. The shooting mechanic is still there. I think we said we going to scrap it


Fix those and then we can merge into dev, it should be effected by a pull of the dev


https://github.com/MashdorDev/unbreaded/assets/56084381/2c75a943-85be-4251-a824-e1929d76bd97

**Comment by SafakOnol** [comment]
camera removed from BP_Character

**Review by MashdorDev — APPROVED** [review]
SIck! 
HowdyGIF

**Pull request merged**
