### PR TITLE
fixed access violation

### PR DESCRIPTION
**Pull request by antoniukoff**
## What
fixed access violation regarding AI Manager

## How
Added Blueprint Callavle function node that removes the destroyed AI character from the Ai Manager Agents list when GAS is invoked.

close issue #180

### CODE REVIEW

**Review by MashdorDev — CHANGES_REQUESTED** [review]
Writing again as it seems that it wasn't seen before -



Hey @antoniukoff, great job on the feature!

I know @GageM working on the core level, is this chance for the level is crucial for the feature or can we do without?

**Comment by MashdorDev** [comment]
fixed #180

**Comment by MashdorDev** [comment]
Hey @antoniukoff, so this is what happened to me when I tested the branch; I got this from `SChacarter.cpp`; we can try to solve it together to see what happens and why



https://github.com/MashdorDev/unbreaded/assets/56084381/7ce6b783-5a5d-4070-8d21-3b5f09ba0482

**Comment by antoniukoff** [comment]
@MashdorDev fixed

**Review by MashdorDev — APPROVED** [review]
amazing chef kiss

ChefsKissFrenchChefGIF

**Pull request merged**
